### ISSUE TITLE
0.11.2.cl1.b2 build problem (boost) on Debian 7

### ISSUE THREAD

**Issue by ftrader** [bitcoinclassic/bitcoinclassic#79]
I was trying to build using the sources released in bitcoinclassic-0.11.2.cl1.b2.tar.gz on a Debian 7 (Wheezy) 64 bit system.

I use a slightly non-standard configuration to do my builds, which has so far worked for Core, XT, Unlimited etc. I don't think it matters, it's just because I have compiled BDB myself. My configure command looks like:

./configure --prefix=/home/ftrader --with-gui=qt4 --with-pic --disable-shared --enable-cxx LDFLAGS=-L/usr/local/BerkeleyDB.4.8/lib/ CPPFLAGS=-I/usr/local/BerkeleyDB.4.8/include/

On to the actual problem:

When I run 'make', it fails with:

<verbatim>CXX    bitcoind-bitcoind.o
In file included from bitcoind.cpp:9:0:
main.h:38:28: fatal error: boost/atomic.hpp: No such file or directory
 #include <boost/atomic.hpp>
                            ^
compilation terminated.
</verbatim>

I suspect my Debian 7 Boost version (1.49) is too old.
The build-unix.md only mentions to install libboost-all-dev without specifying a minimum version, and the configure process did not flag my Boost as inadequate.

**Comment by ftrader** [comment]
After trying to fix the problem by passing custom LDFLAGS to configure, it seems those LDFLAGS are ignored (I am trying to point it at a custom-installed Boost 1.58 in /opt/boost_1_58).

**Comment by ftrader** [comment]
Build worked with custom-built Boost 1.58 installed in /opt/boost_1_58 and adding "-Wl,-rpath-link,/opt/boost_1_58/lib" to my LDFLAGS. Ran a "make check" and passed everything, and bitcoin-qt ran up fine using my existing .bitcoin/ folder.

In case it helps any Debian 7 users, my final configure command looked like this:

<verbatim>
./configure CXXFLAGS=-I/opt/boost_1_58/include --prefix=/home/ftrader --with-gui=qt4 --with-pic --disable-shared --enable-cxx LDFLAGS=-Wl,-rpath-link,/opt/boost_1_58/lib -Wl,-rpath,/opt/boost_1_58/lib -Wl,-rpath,/usr/local/BerkeleyDB.4.8/lib -L/usr/local/BerkeleyDB.4.8/lib/ CPPFLAGS=-I/usr/local/BerkeleyDB.4.8/include/ --with-boost=/opt/boost_1_58 --with-boost-libdir=/opt/boost_1_58/lib
</verbatim>

Of course you'll still need to install your own BDB 4.8 and Boost 1.58, but it works in the end.

It would still be helpful to accurately document the minimum Boost version which is usable for building the Bitcoin software (anyone who has successfully built using < 1.58, please share your experience!)

**Comment by mmouse-** [comment]
I managed to build it on Debian 8 (jessy) with
./configure --with-incompatible-bdb
That should be Boost 1.55 and BDB 5.3. 
But be careful with this if you have an existing wallet.
